volumes:
  pg_data:

services:
  db:
    image: postgres:15-alpine
    container_name: caseflow_db
    restart: always
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: caseflow_app
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
